### ISSUE TITLE
FSOS 2.2

### ISSUE THREAD

**Issue by adn77** [napalm-automation-community/napalm-fsos-ssh#15]
I am planning to buy a couple of S3900 48T6S-R.
That model ships with FSOS 2.2, which appears to differ from v1.7 you are using.

There is no *show system* and it's *show interface* instead of *show interfaces*.

I probably could create a fsos2-ssh from your code but maybe you can think of another way - supporting both versions from a single module?!

**Comment by adn77** [comment]
My Python skills are rather limited, but I guess I will manage 😉

What do you think would be the best way to distinguish the two? Try your fact gathering and if it errors, try something else?

**Comment by M0NsTeRRR** [comment]
I can help you with that don't worry, if you give me the output of your command I guess I could manage it.
I think we could manage this way : when SSH connection is start, gather the fact and set the version as an attribute, your switch support fact gahering too ?

**Comment by adn77** [comment]
As I said, the commands here https://github.com/napalm-automation-community/napalm-fsos-ssh/blob/e0fdf976c279aa2aa9b2c4ffa2518a89d857cdd6/napalm_fsos_ssh/fsos.py#L273 differ already.
No *show system*, info is contained in the output of *show version* instead.

Having a try/catch would probably allow for testing v2.2 if v1.7 commands fail.
I'll put some outputs together tomorrow when I have access to the switches.

Thanks a lot for offering to help - I 'd be lost otherwise 😃

Btw. I tried looking for the initial *enable* but didn't find where it is sent in your code.

**Comment by M0NsTeRRR** [comment]
Oh okay. Do you know if every command has changed ? If yes maybe we should split the code in 2 class v1 and v2 and at the login detect the version to load the appropriate class for the custom command. I need to check how to handle unit test.

There is no enable command on my firmware (default mode after ssh).

**Comment by adn77** [comment]
Looks like the commands and the output changed quite a bit.

`show version`

```
Fiberstore Co., Limited Internetwork Operating System Software
S3900-48T6S-R Series Software, Version 2.2.0F Build 107821, RELEASE SOFTWARE
Copyright (c) 2021 by FS.COM All Rights Reserved
Compiled: 2022-12-22 9:40:43 by SYS, Image text-base: 0x80010000
ROM: System Bootstrap, Version 0.1.9,hardware version:A
Serial num:CG2206232992N00xxx, ID num:0020083905324
System image file is "Switch.bin"
FS S3900-48T6S-R RISC
524288K bytes of memory,16384K bytes of flash
Base ethernet MAC Address: 64:9d:99:xx:xx:xx
PCB version:J
snmp info:
  vend_ID:52642   product_ID:2039   system_ID:1.3.6.1.4.1.52642.1.2039.0
fs01.local uptime is 8:00:07:31, The current time: 2023-2-16 8:38:40
 Reboot history information:
  No. 1: System is rebooted by power-on
```
`show interface brief`

```
Port    Description           Status    Vlan        Duplex   Speed    Type
g0/1                          down      1           auto     auto     Giga-TX
g0/2                          down      1           auto     auto     Giga-TX
g0/3                          down      1           auto     auto     Giga-TX
g0/4                          down      1           auto     auto     Giga-TX
g0/5                          down      1           auto     auto     Giga-TX
g0/6                          up        1           full     1000Mb   Giga-TX
...
g0/48                         down      1           auto     auto     Giga-TX
tg0/49                        down      1           full     10000Mb  10Giga-FX
tg0/50                        up        1           full     10000Mb  10Giga-FX-SFP
tg0/51                        down      1           full     10000Mb  10Giga-FX
tg0/52                        down      1           full     10000Mb  10Giga-FX
tg0/53                        down      1           full     10000Mb  10Giga-FX
tg0/54                        down      1           full     10000Mb  10Giga-FX
v1                            up
n0                            up
```

I would feel comfortable rewriting the textfsm templates.
In regard to whether it would be better to create another class or handling both cases for each command in your existing class, it's all up to you :)

Could you create a branch where you would prepare how you imagine the version splitting would work?
I would then fork and send you PRs with how far I can get.

Thanks again for the effort!

Alex

**Comment by M0NsTeRRR** [comment]
Okay yes it's really differents. Sure I will check it. FS answered my email today and they will not upgrade my switch to v2.

**Comment by M0NsTeRRR** [comment]
I've discussed with some others devs and the idea of merging both driver in one could be a good idea if they share some commands but as you said they have nothing in common. I will ask napalm repository what do they think about creating an other repository for v2 (I will help you in case we do that don't worry)

**Comment by M0NsTeRRR** [comment]
Also i've rechecked today but there is an enable mode.

In the documentation `If a privilege level is not configured password, then no
authentication is performed when a user entering this privilege level.` there is an issue right there, if I type `level 15` in the enable password command `level 15` is not saved in config and it's not asking me to type it with an user with privilege 15 ... a new ticket to open I guess.

**Comment by adn77** [comment]
I started a test, trying to get an output for **get_facts**. Unfortunately the *enable* mode is already blocking me.

Looks like netmiko can take care of this, so I tried:
```
    def __init__(
        self,
        hostname: str,
        username: str,
        password: str,
        timeout: int = 60,
        optional_args: Dict[str, Any] = None,
    ) -> None:
        self.device = None
        self.hostname = hostname
        self.username = username
        self.password = password
        self.timeout = timeout
        self.vendor = "Fiberstore"
        self.device_type = "generic"

        if optional_args is None:
            optional_args = {
                "secret": ""
            }

        self.netmiko_optional_args = netmiko_args(optional_args)
        self.netmiko_optional_args.setdefault("port", 22)

    def open(self) -> None:
        self.device = self._netmiko_open(
            self.device_type, netmiko_optional_args=self.netmiko_optional_args
        )
        self.device.enable()
```
=> Setting an empty enable secret
=> trying to call device.enable after the connection has been set up

From the debug output I can see that the commands are not sent in enable mode 😦 
```
2023-02-21 16:43:56,789 - napalm - DEBUG - get_facts - Calling with args: (<napalm_fsos_ssh.fsos.FsosDriver object at 0x7f788232f2e0>,), {}
show version
^
Unknown command
show interface brief
^
Unknown command
```

**Comment by M0NsTeRRR** [comment]
Hello @adn77,

I've added fix for enable mode in the driver.  If  you take the latest code it should works.

```py
from napalm_fsos_ssh.fsos import FsosDriver

driver = FsosDriver("192.168.0.1", "username", "admin", 60, {"secret": "enable password"})
driver.open()
driver.get_arp_table()
```

If your  user doesn't have access to enable mode (not needed)
```py
from napalm_fsos_ssh.fsos import FsosDriver

driver = FsosDriver("192.168.0.1", "username", "admin", 60, {"force_no_enable": True})
driver.open()
driver.get_environment()
```

I'm still waiting an answer for my driver request for v2

**Comment by adn77** [comment]
Getting one step further 😄 

I have two commands in **get_facts** and modified the templates accordingly.
1. *show version* => `[{'os_version': '2.2.0F Build 107821', 'model': 'S3900-48T6S-R', 'serial_number': 'CG2206232992xxxxxx', 'uptime': '15:12:58:49', 'hostname': 'fs01'}]`
2. *show interface brief* => `Pattern not detected: 'fs01\\#' in output.`

How can I get more debugging output, e.g. the Netmiko session_log.
Setting it as extra_args didn't work 😦

**Comment by M0NsTeRRR** [comment]
Hello,

Cool !

`driver = FsosDriver("192.168.0.1", "username", "admin", 60, {"session_log": "netmiko_session.log")`

**Comment by M0NsTeRRR** [comment]
Try it like this `napalm --user admin --password admin -v napalm_fsos_ssh --debug 192.168.1.1 --optional_args session_log=netmiko_session.log`

**Comment by adn77** [comment]
Doesn't work ☹️ 
```
napalm --user admin --password admin -v napalm_fsos_ssh --optional_args session_log=netmiko_session.log --debug 192.168.1.1
2023-02-24 17:58:18,742 - napalm - DEBUG - Starting napalm's debugging tool
2023-02-24 17:58:18,743 - napalm - DEBUG - Gathering napalm packages
2023-02-24 17:58:18,743 - napalm - DEBUG - napalm-fsos-ssh==0
2023-02-24 17:58:18,743 - napalm - DEBUG - napalm==4.0.0
2023-02-24 17:58:18,743 - napalm - DEBUG - get_network_driver - Calling with args: ('napalm_fsos_ssh',), {}
2023-02-24 17:58:18,825 - napalm - DEBUG - get_network_driver - Successful
Traceback (most recent call last):
  File "/home/alex/.cache/pypoetry/virtualenvs/napalm-fsos-ssh-k1IlQboL-py3.9/bin/napalm", line 8, in <module>
    sys.exit(main())
  File "/home/alex/.cache/pypoetry/virtualenvs/napalm-fsos-ssh-k1IlQboL-py3.9/lib/python3.9/site-packages/napalm/base/clitools/cl_napalm.py", line 308, in main
    run_tests(args)
  File "/home/alex/.cache/pypoetry/virtualenvs/napalm-fsos-ssh-k1IlQboL-py3.9/lib/python3.9/site-packages/napalm/base/clitools/cl_napalm.py", line 269, in run_tests
    optional_args = helpers.parse_optional_args(args.optional_args)
  File "/home/alex/.cache/pypoetry/virtualenvs/napalm-fsos-ssh-k1IlQboL-py3.9/lib/python3.9/site-packages/napalm/base/clitools/helpers.py", line 131, in parse_optional_args
    return {
  File "/home/alex/.cache/pypoetry/virtualenvs/napalm-fsos-ssh-k1IlQboL-py3.9/lib/python3.9/site-packages/napalm/base/clitools/helpers.py", line 132, in <dictcomp>
    x.split("=")[0]: ast.literal_eval(x.split("=")[1])
  File "/usr/lib/python3.9/ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.9/ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.9/ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.9/ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "/usr/lib/python3.9/ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <ast.Attribute object at 0x7f4ab6f2e460>
```

**Comment by M0NsTeRRR** [comment]
Ok, you need to add quote around log filename because https://github.com/napalm-automation/napalm/blob/master/napalm/base/clitools/helpers.py#L132

Like `napalm --user admin --password admin -v napalm_fsos_ssh --debug 192.168.1.1 --optional_args session_log='netmiko_session.log'`

**Comment by adn77** [comment]
That worked. 😄 
Since the my problem lies with the `terminal length` command I'll continue in the other thread.
