### ISSUE TITLE
library can't call from Napalm

### ISSUE THREAD

**Issue by lkthomas** [napalm-automation-community/napalm-fsos-ssh#5]
``
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
>>> import napalm_fsos_ssh
>>> dir(napalm_fsos_ssh)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> napalm_fsos_ssh
<module 'napalm_fsos_ssh' from '/opt/netbox/venv/lib/python3.8/site-packages/napalm_fsos_ssh/__init__.py'>
>>> import importlib
>>> importlib.import_module("napalm_fsos_ssh")
<module 'napalm_fsos_ssh' from '/opt/netbox/venv/lib/python3.8/site-packages/napalm_fsos_ssh/__init__.py'>
>>> get_network_driver('fsos_ssh')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/netbox/venv/lib/python3.8/site-packages/napalm/base/__init__.py", line 110, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.fsos_ssh".
>>> get_network_driver('fsos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/netbox/venv/lib/python3.8/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
napalm.base.exceptions.ModuleImportError: Cannot import "fsos". Is the library installed?
``

**Comment by lkthomas** [comment]
why "__init__.py" file is empty?

**Comment by M0NsTeRRR** [comment]
Hello,

Thanks you for opening an issue, I didn't have time to test it with napalm software, only as standalone driver :)
